version: "3.9"

networks:
  web-app:
    driver: bridge

services:
  database:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "cardtracker_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app-data:/var/lib/postgresql/data
    networks:
      - web-app
  
  # backend:
  #   image: backend
  #   depends_on:
  #     - "database"
  #   container_name: backend
  #   ports:
  #     - "5000:80"
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Server=database;Port=5432;Database=cardtracker_db;User Id=postgres;Password=postgres
  #     - ASPNETCORE_URLS=http://+:80
  #   networks:
  #     - web-app
volumes:
  app-data: